#
# Copyright (C) 2024-2026 BuildBureau team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Area labels - identify which part of the codebase is affected

area/agent:
  - changed-files:
      - any-glob-to-any-file:
          - internal/agent/**/*
          - pkg/types/agent.go

area/memory:
  - changed-files:
      - any-glob-to-any-file:
          - internal/memory/**/*
          - pkg/types/memory.go

area/llm:
  - changed-files:
      - any-glob-to-any-file:
          - internal/llm/**/*

area/grpc:
  - changed-files:
      - any-glob-to-any-file:
          - internal/grpc/**/*
          - pkg/protocol/**/*

area/config:
  - changed-files:
      - any-glob-to-any-file:
          - internal/config/**/*
          - config.yaml
          - agents/**/*.yaml

area/tui:
  - changed-files:
      - any-glob-to-any-file:
          - internal/tui/**/*

area/slack:
  - changed-files:
      - any-glob-to-any-file:
          - internal/slack/**/*

area/examples:
  - changed-files:
      - any-glob-to-any-file:
          - examples/**/*

area/bootstrap:
  - changed-files:
      - any-glob-to-any-file:
          - bootstrap/**/*

area/docker:
  - changed-files:
      - any-glob-to-any-file:
          - Dockerfile
          - docker-compose.yml
          - .dockerignore

area/makefile:
  - changed-files:
      - any-glob-to-any-file:
          - Makefile

# Type labels - identify the type of change

type/ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*

type/documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - docs/**/*

type/test:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*_test.go"

type/dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - go.mod
          - go.sum

# Language labels

language/go:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.go"

language/yaml:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.yaml"
          - "**/*.yml"

language/shell:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.sh"

language/proto:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.proto"

# Size labels - automatically added based on PR size

size/XS:
  - changed-files:
      - 1-9

size/S:
  - changed-files:
      - 10-29

size/M:
  - changed-files:
      - 30-99

size/L:
  - changed-files:
      - 100-499

size/XL:
  - changed-files:
      - 500+
