// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/protocol/agent.proto

package protocol

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskRequest represents a task to be processed
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	FromAgent     string                 `protobuf:"bytes,4,opt,name=from_agent,json=fromAgent,proto3" json:"from_agent,omitempty"`
	ToAgent       string                 `protobuf:"bytes,5,opt,name=to_agent,json=toAgent,proto3" json:"to_agent,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Priority      int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_pkg_protocol_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_agent_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskRequest) GetFromAgent() string {
	if x != nil {
		return x.FromAgent
	}
	return ""
}

func (x *TaskRequest) GetToAgent() string {
	if x != nil {
		return x.ToAgent
	}
	return ""
}

func (x *TaskRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TaskRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// TaskResponse represents the response from processing a task
type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_pkg_protocol_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_agent_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TaskResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StatusRequest requests the status of an agent
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pkg_protocol_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_agent_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// StatusResponse provides the status of an agent
type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ActiveTasks    int32                  `protobuf:"varint,3,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	CompletedTasks int32                  `protobuf:"varint,4,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_protocol_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *StatusResponse) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

// NotificationRequest sends a notification
type NotificationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FromAgent        string                 `protobuf:"bytes,1,opt,name=from_agent,json=fromAgent,proto3" json:"from_agent,omitempty"`
	ToAgent          string                 `protobuf:"bytes,2,opt,name=to_agent,json=toAgent,proto3" json:"to_agent,omitempty"`
	NotificationType string                 `protobuf:"bytes,3,opt,name=notification_type,json=notificationType,proto3" json:"notification_type,omitempty"`
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_pkg_protocol_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_agent_proto_rawDescGZIP(), []int{4}
}

func (x *NotificationRequest) GetFromAgent() string {
	if x != nil {
		return x.FromAgent
	}
	return ""
}

func (x *NotificationRequest) GetToAgent() string {
	if x != nil {
		return x.ToAgent
	}
	return ""
}

func (x *NotificationRequest) GetNotificationType() string {
	if x != nil {
		return x.NotificationType
	}
	return ""
}

func (x *NotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// NotificationResponse acknowledges a notification
type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_pkg_protocol_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_agent_proto_rawDescGZIP(), []int{5}
}

func (x *NotificationResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *NotificationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_protocol_agent_proto protoreflect.FileDescriptor

const file_pkg_protocol_agent_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/protocol/agent.proto\x12\bprotocol\"\xc3\x02\n" +
	"\vTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"from_agent\x18\x04 \x01(\tR\tfromAgent\x12\x19\n" +
	"\bto_agent\x18\x05 \x01(\tR\atoAgent\x12?\n" +
	"\bmetadata\x18\x06 \x03(\v2#.protocol.TaskRequest.MetadataEntryR\bmetadata\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xec\x01\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12@\n" +
	"\bmetadata\x18\x04 \x03(\v2$.protocol.TaskResponse.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\rStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x8f\x01\n" +
	"\x0eStatusResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\factive_tasks\x18\x03 \x01(\x05R\vactiveTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x04 \x01(\x05R\x0ecompletedTasks\"\x9c\x02\n" +
	"\x13NotificationRequest\x12\x1d\n" +
	"\n" +
	"from_agent\x18\x01 \x01(\tR\tfromAgent\x12\x19\n" +
	"\bto_agent\x18\x02 \x01(\tR\atoAgent\x12+\n" +
	"\x11notification_type\x18\x03 \x01(\tR\x10notificationType\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12G\n" +
	"\bmetadata\x18\x05 \x03(\v2+.protocol.NotificationRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x14NotificationResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xd5\x01\n" +
	"\fAgentService\x12<\n" +
	"\vProcessTask\x12\x15.protocol.TaskRequest\x1a\x16.protocol.TaskResponse\x12>\n" +
	"\tGetStatus\x12\x17.protocol.StatusRequest\x1a\x18.protocol.StatusResponse\x12G\n" +
	"\x06Notify\x12\x1d.protocol.NotificationRequest\x1a\x1e.protocol.NotificationResponseB,Z*github.com/kpango/BuildBureau/pkg/protocolb\x06proto3"

var (
	file_pkg_protocol_agent_proto_rawDescOnce sync.Once
	file_pkg_protocol_agent_proto_rawDescData []byte
)

func file_pkg_protocol_agent_proto_rawDescGZIP() []byte {
	file_pkg_protocol_agent_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_agent_proto_rawDesc), len(file_pkg_protocol_agent_proto_rawDesc)))
	})
	return file_pkg_protocol_agent_proto_rawDescData
}

var file_pkg_protocol_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_protocol_agent_proto_goTypes = []any{
	(*TaskRequest)(nil),          // 0: protocol.TaskRequest
	(*TaskResponse)(nil),         // 1: protocol.TaskResponse
	(*StatusRequest)(nil),        // 2: protocol.StatusRequest
	(*StatusResponse)(nil),       // 3: protocol.StatusResponse
	(*NotificationRequest)(nil),  // 4: protocol.NotificationRequest
	(*NotificationResponse)(nil), // 5: protocol.NotificationResponse
	nil,                          // 6: protocol.TaskRequest.MetadataEntry
	nil,                          // 7: protocol.TaskResponse.MetadataEntry
	nil,                          // 8: protocol.NotificationRequest.MetadataEntry
}
var file_pkg_protocol_agent_proto_depIdxs = []int32{
	6, // 0: protocol.TaskRequest.metadata:type_name -> protocol.TaskRequest.MetadataEntry
	7, // 1: protocol.TaskResponse.metadata:type_name -> protocol.TaskResponse.MetadataEntry
	8, // 2: protocol.NotificationRequest.metadata:type_name -> protocol.NotificationRequest.MetadataEntry
	0, // 3: protocol.AgentService.ProcessTask:input_type -> protocol.TaskRequest
	2, // 4: protocol.AgentService.GetStatus:input_type -> protocol.StatusRequest
	4, // 5: protocol.AgentService.Notify:input_type -> protocol.NotificationRequest
	1, // 6: protocol.AgentService.ProcessTask:output_type -> protocol.TaskResponse
	3, // 7: protocol.AgentService.GetStatus:output_type -> protocol.StatusResponse
	5, // 8: protocol.AgentService.Notify:output_type -> protocol.NotificationResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_protocol_agent_proto_init() }
func file_pkg_protocol_agent_proto_init() {
	if File_pkg_protocol_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_agent_proto_rawDesc), len(file_pkg_protocol_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_agent_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_agent_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_agent_proto_msgTypes,
	}.Build()
	File_pkg_protocol_agent_proto = out.File
	file_pkg_protocol_agent_proto_goTypes = nil
	file_pkg_protocol_agent_proto_depIdxs = nil
}
